<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ab0f128de9cd',
	'title' => __('Colored Index', 'simrishamn'),
	'fields' => array(
		array(
			'key' => 'field_5ac74472c652b',
			'label' => __('Format', 'simrishamn'),
			'name' => 'format',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Standard',
				'info' => 'Info-Box',
			),
			'default_value' => array(
				0 => 'default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ab0f128e55af',
			'label' => __('Columns', 'simrishamn'),
			'name' => 'index_columns',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'grid-md-12' => '1',
				'grid-md-6' => '2',
				'grid-md-4' => '3',
				'grid-md-3' => '4',
			),
			'default_value' => array(
				0 => 'grid-md-12',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ab0f128e553d',
			'label' => __('Settings', 'simrishamn'),
			'name' => 'colored-index',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 4,
			'layout' => 'block',
			'button_label' => __('Add Row', 'simrishamn'),
			'sub_fields' => array(
				array(
					'key' => 'field_5ab0f128e845e',
					'label' => __('Link type', 'simrishamn'),
					'name' => 'link_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'internal' => 'Internal',
						'external' => 'External',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5ab0f128e84fb',
					'label' => __('Page', 'simrishamn'),
					'name' => 'link_url',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ab0f128e845e',
								'operator' => '==',
								'value' => 'internal',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5ab0f128e857f',
					'label' => __('Link url', 'simrishamn'),
					'name' => 'link_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ab0f128e845e',
								'operator' => '==',
								'value' => 'external',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ab0f128e861a',
					'label' => __('Image', 'simrishamn'),
					'name' => 'image-p',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ac74472c652b',
								'operator' => '==',
								'value' => 'default',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5ab0f128e8699',
					'label' => __('Upload image', 'simrishamn'),
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ab0f128e861a',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5ab0f128e8730',
					'label' => __('Title', 'simrishamn'),
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ac74472c652b',
								'operator' => '==',
								'value' => 'default',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 15,
				),
				array(
					'key' => 'field_5ab0f128e8863',
					'label' => __('Summary (150)', 'simrishamn'),
					'name' => 'lead',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ab0f128e861a',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 150,
					'rows' => 5,
					'new_lines' => '',
				),
				array(
					'key' => 'field_5ab0f3e899316',
					'label' => __('Summary (250)', 'simrishamn'),
					'name' => 'lead',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ab0f128e861a',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 250,
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_5ab0f4b3d636c',
					'label' => __('Color', 'simrishamn'),
					'name' => 'color',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'red' => 'Red',
						'blue' => 'Blue',
						'light-blue' => 'Light Blue',
						'green' => 'Green',
						'gray' => 'Gray',
						'blue-gray' => 'Blue/Gray',
					),
					'default_value' => array(
						0 => 'blue',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ab13d52cc9a7',
					'label' => __('Button Text', 'simrishamn'),
					'name' => 'btn-text',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Läs Mer',
					'placeholder' => 'Läs Mer',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'mod-colored-index',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;